In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

TypeError: ignored

In [ ]:
path ='Book1.csv'

In [ ]:
df = pd.read_csv(path)

In [ ]:
df

student  Test score   IQ  Study Hours
0        1         100  110           40
1        2          90  120           30
2        3          80  100           20
3        4          70   90            0
4        5          60   80           10

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lm = LinearRegression()
lm

LinearRegression()

In [ ]:
Z = df[['IQ','Study Hours']]

In [ ]:
featureset = df[['IQ','Study Hours']]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
x = featureset.values #returns a numpy array
min_max_scaler = MinMaxScaler()
feature_mtx = min_max_scaler.fit_transform(x)
Z = feature_mtx
feature_mtx [0:5]

array([[0.75, 1.  ],
       [1.  , 0.75],
       [0.5 , 0.5 ],
       [0.25, 0.  ],
       [0.  , 0.25]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
x = np.array(df[['Test score']]) #returns a numpy array
min_max_scaler = MinMaxScaler()
feature_mtx = min_max_scaler.fit_transform(x)
df[['Test score']] = feature_mtx
feature_mtx [0:5]

array([[1.  ],
       [0.75],
       [0.5 ],
       [0.25],
       [0.  ]])

In [ ]:
lm.fit(Z, df['Test score'])

LinearRegression()

In [ ]:
yhat = lm.predict(Z)
yhat

array([0.875, 0.875, 0.5  , 0.125, 0.125])

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
print(lm.intercept_)
print(lm.coef_)

2.220446049250313e-16
[0.5 0.5]


In [ ]:
mse = mean_squared_error(df[['Test score']], yhat)
print('The mean square error of price and predicted value is: ',mse)

The mean square error of price and predicted value is:  0.012500000000000002
