In [ ]:
from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
uploaded = files.upload()

Saving Book1.csv to Book1.csv


In [ ]:
path ='Book1.csv'
df = pd.read_csv(path)
df

student  Test score   IQ  Study Hours
0        1         100  110           40
1        2          90  120           30
2        3          80  100           20
3        4          70   90            0
4        5          60   80           10

In [ ]:
X = df[["IQ","Study Hours"]]
Y = df["Test score"]

In [ ]:
x.shape

(5, 2)

In [ ]:
col = np.ones((5,1))
col

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
x = np.append(col,x, axis = 1)
x

array([[  1.,   1., 110.,  40.],
       [  1.,   1., 120.,  30.],
       [  1.,   1., 100.,  20.],
       [  1.,   1.,  90.,   0.],
       [  1.,   1.,  80.,  10.]])

In [ ]:
x.shape

(5, 4)

In [ ]:
y = df[["Test score"]]


In [ ]:
x = np.array(X)
x

array([[110,  40],
       [120,  30],
       [100,  20],
       [ 90,   0],
       [ 80,  10]])

In [ ]:
y = np.array(y)
y

array([100,  90,  80,  70,  60])

In [ ]:
x_trans = x.transpose()
x_trans

array([[110, 120, 100,  90,  80],
       [ 40,  30,  20,   0,  10]])

In [ ]:
xmulti = np.matmul(x_trans,x)
xmulti

array([[51000, 10800],
       [10800,  3000]])

In [ ]:
xinv = np.linalg.inv(xmulti)
xinv

array([[ 8.25082508e-05, -2.97029703e-04],
       [-2.97029703e-04,  1.40264026e-03]])

In [ ]:
finalx = np.matmul(xinv,x_trans)
finalx

array([[-0.00280528,  0.0009901 ,  0.00231023,  0.00742574,  0.00363036],
       [ 0.02343234,  0.00643564, -0.00165017, -0.02673267, -0.00973597]])

In [ ]:
b = np.matmul(finalx, y)
b

array([0.7310231, 0.3349835])