In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart.csv


In [ ]:
df = pd.read_csv("heart.csv")
df.head()

age  gender  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0   63       1   3       145   233    1        0      150      0      2.3   
1   37       1   2       130   250    0        1      187      0      3.5   
2   41       0   1       130   204    0        0      172      0      1.4   
3   56       1   1       120   236    0        1      178      0      0.8   
4   57       0   0       120   354    0        1      163      1      0.6   

   slope  ca  thal  target  
0      0   0     1       1  
1      0   0     2       1  
2      2   0     2       1  
3      2   0     2       1  
4      2   0     2       1

In [ ]:
X = df.drop("target",1)
Y = df["target"]

<ipython-input-4-db297d0c0a06>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop("target",1)


In [ ]:
corr=df.corr()
cor_target = abs(corr["target"])
relevant_features = cor_target[cor_target>=0.35]
relevant_features

cp         0.433798
thalach    0.421741
exang      0.436757
oldpeak    0.430696
ca         0.391724
target     1.000000
Name: target, dtype: float64

In [ ]:
X_new = df[['cp','thalach','exang','oldpeak','slope','ca','thal']]
X_new

cp  thalach  exang  oldpeak  slope  ca  thal
0     3      150      0      2.3      0   0     1
1     2      187      0      3.5      0   0     2
2     1      172      0      1.4      2   0     2
3     1      178      0      0.8      2   0     2
4     0      163      1      0.6      2   0     2
..   ..      ...    ...      ...    ...  ..   ...
298   0      123      1      0.2      1   0     3
299   3      132      0      1.2      1   0     3
300   0      141      0      3.4      1   2     3
301   0      115      1      1.2      1   1     3
302   1      174      0      0.0      1   1     2

[303 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X_new, Y, test_size=0.3, random_state=5)
print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

Train set: (212, 7) (212,)
Test set: (91, 7) (91,)


In [ ]:
from sklearn import svm
clf = svm.SVC(kernel = 'linear')
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
clf.intercept_

array([0.05457661])

In [ ]:
obj = clf.fit(X_train,y_train)

In [ ]:
yhat = clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,yhat)
accuracy_score(y_train,obj.predict(X_train))

0.8207547169811321

In [ ]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

print("Train set Accuracy: ", metrics.accuracy_score(y_train,clf.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test,clf.predict(X_test)))

Train set Accuracy:  0.8207547169811321
Test set Accuracy:  0.8901098901098901


In [ ]:
yhat=obj.predict([[12,34,54,1,34,1,1]])
yhat

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
clf.coef_

array([[ 0.45750622,  0.01129277, -0.76558231, -0.25280502,  0.24411481,
        -0.65216713, -0.70914787]])

In [ ]:
bias = np.array(clf.intercept_)

In [ ]:
weight= np.array(clf.coef_)

In [ ]:
testdata = np.array(X_test)

In [ ]:
y_new = np.sign(np.dot(testdata, weight.transpose()) + bias)

In [ ]:
y_new

array([[ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
      

In [ ]:
X_test[1:2]
value = [2,187,0,3.5,0,0,2]
v = np.array(value)

In [ ]:
y_new=np.sign(np.dot(v,weight.transpose()) + bias)
y_new

array([1.])